In [ ]:
data = open("/content/text.txt").read()

print(data[:500])
#Basically iam doing is printing the first 500 words in our dataset

machine learning is powerful
machine learning is interesting
machine learning is transforming the world
machine learning helps computers learn
machine learning is part of artificial intelligence
deep learning is a subset of machine learning
deep learning uses neural networks
deep learning learns from large data
artificial intelligence is the future
artificial intelligence helps automation
artificial intelligence is used in healthcare
artificial intelligence is used in robotics
data science analy


In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()

tokenizer.fit_on_texts([data])

total_words = len(tokenizer.word_index) + 1

print("Total Words:", total_words)
#The computer cannot understand words, so we convert:These sentence into nnumbers,This is called Tokenization.

Total Words: 170


In [ ]:
input_sequences = []

for line in data.split('\n'):

    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

print(input_sequences[:10])
#What this code does
#data.split('\n')

# Splits the dataset line by line

# texts_to_sequences

# Converts words → numbers

# token_list[:i+1]

# Creates sequences

[[8, 2], [8, 2, 7], [8, 2, 7, 54], [8, 2], [8, 2, 7], [8, 2, 7, 79], [8, 2], [8, 2, 7], [8, 2, 7, 80], [8, 2, 7, 80, 39]]


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_sequence_len = max([len(x) for x in input_sequences])

input_sequences = pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre')

print(input_sequences[:10])

#We are actually doing padding here


# What this code does
# max_sequence_len
# Finds the longest sequence.

# pad_sequences
# Adds 0 in the beginning.

[[ 0  0  0  0  0  0  0  8  2]
 [ 0  0  0  0  0  0  8  2  7]
 [ 0  0  0  0  0  8  2  7 54]
 [ 0  0  0  0  0  0  0  8  2]
 [ 0  0  0  0  0  0  8  2  7]
 [ 0  0  0  0  0  8  2  7 79]
 [ 0  0  0  0  0  0  0  8  2]
 [ 0  0  0  0  0  0  8  2  7]
 [ 0  0  0  0  0  8  2  7 80]
 [ 0  0  0  0  8  2  7 80 39]]


In [ ]:
xs = input_sequences[:,:-1] #Input words
ys = input_sequences[:,-1] #next word to predict
# Split Input (X) and Output (y)

In [ ]:
from tensorflow.keras.utils import to_categorical

ys = to_categorical(ys, num_classes=total_words)

print(ys.shape)

#From the output - Meaning that 601 training samples and 170 vocabulary samples

(601, 170)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

model = Sequential()

model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(SimpleRNN(150))

model.add(Dense(total_words, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

#As in the output:
# Param  : 0
# (unbuilt)
# Total params: 0

# This means:

# The neural network architecture is defined, but
# TensorFlow has not initialized the weights yet.

# So the model is not built yet, which is why parameters show 0.

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

model = Sequential()

model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(SimpleRNN(150))

model.add(Dense(total_words, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.build(input_shape=(None, max_sequence_len-1))
model.summary()

#Frome the output
# What each line means
# Embedding layer
#Converts words into 100-dimensional vectors.
#150 neurons that learn sequence patterns.
#Dense Layer
#Outputs probability for each word in vocabulary.

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 100)         │        17,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 150)            │        37,650 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 170)            │        25,670 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 80,320 (313.75 KB)

 Trainable params: 80,320 (313.75 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from tensorflow.keras.layers import LSTM

model_lstm = Sequential()

model_lstm.add(Embedding(total_words, 100))
model_lstm.add(LSTM(150))
model_lstm.add(Dense(total_words, activation='softmax'))

model_lstm.compile(loss='categorical_crossentropy',
                   optimizer='adam',
                   metrics=['accuracy'])

model_lstm.build(input_shape=(None, max_sequence_len-1))

model_lstm.summary()

#LSTM Implementation

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 100)         │        17,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 170)            │        25,670 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 193,270 (754.96 KB)

 Trainable params: 193,270 (754.96 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model_lstm.fit(xs, ys, epochs=50)
#Training the lstm model

Epoch 1/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 0.0573 - loss: 5.0861
Epoch 2/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0538 - loss: 4.4435
Epoch 3/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0813 - loss: 4.2060
Epoch 4/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.1183 - loss: 4.0667
Epoch 5/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.1687 - loss: 3.8528
Epoch 6/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.2448 - loss: 3.6081
Epoch 7/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3836 - loss: 3.3121
Epoch 8/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4596 - loss: 2.9423
Epoch 9/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.4444 - loss: 2.7665
Epoch 10/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4358 - loss: 2.6237
Epoch 11/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5006 - loss: 2.3760
Epoch 12/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy:

In [ ]:
model.fit(xs, ys, epochs=50, verbose=1)

Epoch 1/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.0396 - loss: 4.9767
Epoch 2/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0566 - loss: 4.3396
Epoch 3/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0883 - loss: 4.0938
Epoch 4/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1694 - loss: 3.7653
Epoch 5/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3236 - loss: 3.3439
Epoch 6/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4012 - loss: 3.0236
Epoch 7/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4807 - loss: 2.6626
Epoch 8/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4913 - loss: 2.4255
Epoch 9/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5414 - loss: 2.0803
Epoch 10/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5248 - loss: 2.0205
Epoch 11/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5261 - loss: 1.8792
Epoch 12/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5488 - 

In [ ]:
# What your training output shows

# Epoch 1: accuracy ≈ 0.03, loss ≈ 4.97

# Epoch 50: accuracy ≈ 0.71, loss ≈ 0.64

# Loss decreased → the model is making fewer mistakes

# Accuracy increased → the model is learning next-word patterns

In [ ]:
def generate_text(seed_text, next_words):

    for _ in range(next_words):

        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')

        predicted = model.predict(token_list, verbose=0)
        predicted_word_index = np.argmax(predicted)

        output_word = tokenizer.index_word[predicted_word_index]

        seed_text = seed_text + " " + output_word

    return seed_text

In [ ]:
print(generate_text("machine learning", 5))

machine learning is used in self driving


In [ ]:
# This means your RNN successfully learned patterns from the dataset and predicted the next words.